sudo: required
dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    packages: lcov

env:
  - BUILD_TYPE=Debug
script:
  - make VERBOSE=1 COVERAGE=1
  - ./xmltest

after_script:
  # Create lcov report
  - lcov --capture --initial --directory . -o app_base.info
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove app_base.info */tests/* --output-file app_base.info
  - lcov --remove coverage.info */tests/* --output-file coverage.info
  - lcov -a app_base.info -a coverage.info -o coverage.info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
